/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colegio;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emanueldemarao
 */
public class Menu_Registrar_docente extends javax.swing.JFrame {
    int x = 0;
    ArrayList<Docente> docentes = new ArrayList();
    ArrayList<Turma> turmas = new ArrayList();
    ArrayList<Disciplina> disciplinas = new ArrayList();
    /**
     * Creates new form Menu_Registrar_docente
     */
    public Menu_Registrar_docente() {
        initComponents();
           for( Docente d: docentes) {
            x = d.getNumero_docente();
        }
        docentes = new Docente().ler();
       turmas = new Turma().ler();
        disciplinas = new Disciplina().ler();
        transferir_dados_disciplina();
        transferir_dados_turma();
        
    }
    
    public void transferir_dados_turma() {
        for(Turma t: turmas) {
            turma.addItem(t.getDescricao());
        }
    }
    
    public void transferir_dados_disciplina() {
        for(Disciplina d: disciplinas) {
            Txt_disciplina.addItem(d.getDescricao());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Txt_disciplina1 = new javax.swing.JTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Txtnome_docente = new javax.swing.JTextField();
        Sexo = new javax.swing.JComboBox();
        Estado = new javax.swing.JComboBox();
        Idade = new javax.swing.JSpinner();
        Botao_registrar_docente = new javax.swing.JButton();
        altura = new javax.swing.JFormattedTextField();
        peso = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        botao_consultar_docente = new javax.swing.JButton();
        botao_eliminar_docente = new javax.swing.JButton();
        Botao_actualizar_dados_docente = new javax.swing.JButton();
        txt_nome_consultar_docente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Listar_docente = new javax.swing.JButton();
        num = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        txtturma1 = new javax.swing.JLabel();
        turma = new javax.swing.JComboBox();
        txtturma2 = new javax.swing.JLabel();
        txtturma3 = new javax.swing.JLabel();
        Txt_disciplina = new javax.swing.JComboBox();
        salario = new javax.swing.JTextField();
        Txt_funcao = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        jFormattedTextField2.setText("jFormattedTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 4, 58));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOME");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("IDADE");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ESTADO CIVIL");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("GÊNERO");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PESO(KG)");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ALTURA(M)");

        Txtnome_docente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtnome_docenteActionPerformed(evt);
            }
        });
        Txtnome_docente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txtnome_docenteKeyTyped(evt);
            }
        });

        Sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));

        Estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro", "Casado" }));

        Idade.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(18), Integer.valueOf(18), null, Integer.valueOf(1)));

        Botao_registrar_docente.setText("REGISTRAR");
        Botao_registrar_docente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_registrar_docenteActionPerformed(evt);
            }
        });

        try {
            altura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            peso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("SALÁRIO");

        botao_consultar_docente.setText("CONSULTAR");
        botao_consultar_docente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_consultar_docenteMouseClicked(evt);
            }
        });
        botao_consultar_docente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_consultar_docenteActionPerformed(evt);
            }
        });

        botao_eliminar_docente.setText("ELIMINAR");
        botao_eliminar_docente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_eliminar_docenteActionPerformed(evt);
            }
        });

        Botao_actualizar_dados_docente.setText("ACTUALIZAR DADOS");
        Botao_actualizar_dados_docente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_actualizar_dados_docenteActionPerformed(evt);
            }
        });

        txt_nome_consultar_docente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nome_consultar_docenteActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\emanu\\AppData\\Local\\Temp\\icons8_search_client_48px.png")); // NOI18N

        Listar_docente.setText("LISTAR");
        Listar_docente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listar_docenteActionPerformed(evt);
            }
        });

        num.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("NÚMERO");

        txtturma1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtturma1.setForeground(new java.awt.Color(255, 255, 255));
        txtturma1.setText("FUNÇÃO");

        txtturma2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtturma2.setForeground(new java.awt.Color(255, 255, 255));
        txtturma2.setText("DISCIPLINA");

        txtturma3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtturma3.setForeground(new java.awt.Color(255, 255, 255));
        txtturma3.setText("TURMA");

        salario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                salarioKeyTyped(evt);
            }
        });

        Txt_funcao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Docente", "Docente(Director_Turma)" }));
        Txt_funcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_funcaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Botao_registrar_docente)
                                .addGap(36, 36, 36)
                                .addComponent(botao_eliminar_docente))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(272, 272, 272)
                                .addComponent(Botao_actualizar_dados_docente)
                                .addGap(46, 46, 46)
                                .addComponent(Listar_docente)
                                .addGap(29, 29, 29)
                                .addComponent(botao_consultar_docente)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_nome_consultar_docente, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(17, 17, 17)
                                .addComponent(Txtnome_docente, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(salario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtturma2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Txt_disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Idade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addComponent(jLabel12)
                                        .addGap(39, 39, 39))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(30, 30, 30)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(txtturma1)
                                .addGap(34, 34, 34)
                                .addComponent(Txt_funcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(34, 34, 34)
                                .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtturma3)
                        .addGap(60, 60, 60)
                        .addComponent(turma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10)
                            .addComponent(Txtnome_docente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel12)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtturma2)
                                    .addComponent(Txt_disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(turma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtturma3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Txt_funcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtturma1))))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Botao_registrar_docente)
                            .addComponent(botao_eliminar_docente)
                            .addComponent(Botao_actualizar_dados_docente)
                            .addComponent(txt_nome_consultar_docente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao_consultar_docente)
                            .addComponent(Listar_docente))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "IDADE", "GÊNERO", "ALTURA", "PESO", "ESTADO CIVIL", "NÚMERO", "DISCIPLINA", "TURMA", "FUNÇÃO", "SALÁRIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);

        jMenu1.setText("MENU");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addGap(144, 144, 144))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
        if (Tabela.getSelectedRow() != -1) {
            Txtnome_docente.setText(Tabela.getValueAt(Tabela.getSelectedRow(), 0).toString());

        } else {

            JOptionPane.showMessageDialog(null, "selecione uma linha  para editar");

        }
    }//GEN-LAST:event_TabelaMouseClicked

    private void Listar_docenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listar_docenteActionPerformed
        DefaultTableModel t = (DefaultTableModel) Tabela.getModel();
        int linhas = t.getRowCount();

        for (int i = linhas-1; i >=0; i--) {
            t.removeRow(i);
        }

        for (Docente dados : docentes) {

            Object[] lista_docente
            = {
                dados.getNome(), dados.getIdade(), dados.getGenero(),
                dados.getAltura(), dados.getPeso(), dados.getEstado_civil(),
                dados.getNumero_docente(), dados.getDisciplina(), dados.getTurma(),
                dados.getFuncao_exercida(),dados.getSalario()
            };
            t.addRow(lista_docente);
        }
    }//GEN-LAST:event_Listar_docenteActionPerformed

    private void txt_nome_consultar_docenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nome_consultar_docenteActionPerformed

    }//GEN-LAST:event_txt_nome_consultar_docenteActionPerformed

    private void Botao_actualizar_dados_docenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_actualizar_dados_docenteActionPerformed
        if(Tabela.getSelectedRow() !=-1) {
            //vai trocar os dados
            Tabela.setValueAt(Txtnome_docente.getText(), Tabela.getSelectedRow(), 0);
            Tabela.setValueAt(((Integer) Idade.getValue()), Tabela.getSelectedRow(), 1);
            Tabela.setValueAt(Sexo.getSelectedItem().toString(), Tabela.getSelectedRow(), 2);
            Tabela.setValueAt(altura.getText(), Tabela.getSelectedRow(), 3);
            Tabela.setValueAt(peso.getText(), Tabela.getSelectedRow(), 4);
            Tabela.setValueAt(Estado.getSelectedItem().toString(), Tabela.getSelectedRow(), 5);
            Tabela.setValueAt(Txt_disciplina.getSelectedItem().toString(), Tabela.getSelectedRow(), 7);
            Tabela.setValueAt(turma.getSelectedItem().toString(), Tabela.getSelectedRow(), 8);
            Tabela.setValueAt(Txt_funcao.getSelectedItem(), Tabela.getSelectedRow(), 9);
            Tabela.setValueAt(salario.getText(), Tabela.getSelectedRow(), 10);

        } else {
            JOptionPane.showMessageDialog(null,"Selecione uma linha para editar");
        }
    }//GEN-LAST:event_Botao_actualizar_dados_docenteActionPerformed

    private void botao_eliminar_docenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_eliminar_docenteActionPerformed

        int index = Tabela.getSelectedRow();
        Tabela.getSelectedRow();
        if (Tabela.getSelectedRow() != -1) {
            DefaultTableModel conteudos = (DefaultTableModel) Tabela.getModel();
            String nome_docente = conteudos.getValueAt(index, 0).toString();
            for (Docente selecionado : docentes) {
                if (selecionado.getNome().equals(nome_docente)) {
                    docentes.remove(selecionado);
                    break;
                }
            }
            conteudos.removeRow(Tabela.getSelectedRow());

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para eliminar algum estudante");
        }
    }//GEN-LAST:event_botao_eliminar_docenteActionPerformed

    private void botao_consultar_docenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_consultar_docenteActionPerformed
        if(txt_nome_consultar_docente.getText().equals(null)) {
            JOptionPane.showMessageDialog(null, "Digite o nome para ser pesquisado");
        }
        txt_nome_consultar_docente.requestFocus();
        DefaultTableModel t = (DefaultTableModel) Tabela.getModel();
        int linhas_tabela = t.getRowCount();

        for (int x = linhas_tabela - 1; x >= 0; x--) {
            t.removeRow(x);
        }

        for (Docente consulta : docentes) {
            if (consulta.getNome().contains(txt_nome_consultar_docente.getText())) {
                Object[] dados_estudante
                = {
                    consulta.getNome(), consulta.getIdade(), consulta.getGenero(),
                    consulta.getAltura(), consulta.getPeso(), consulta.getEstado_civil(),
                    consulta.getNumero_docente(), consulta.getDisciplina(), consulta.getTurma(),
                    consulta.getFuncao_exercida(),consulta.getSalario()
                };
                t.addRow(dados_estudante);
            }
        }
    }//GEN-LAST:event_botao_consultar_docenteActionPerformed

    private void botao_consultar_docenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_consultar_docenteMouseClicked

    }//GEN-LAST:event_botao_consultar_docenteMouseClicked

    private void pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoActionPerformed

    }//GEN-LAST:event_pesoActionPerformed

    private void Botao_registrar_docenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_registrar_docenteActionPerformed
        if(Txtnome_docente.getText().equals("")
            || altura.getText().equals("")
            || peso.getText().equals("")
            || Txt_disciplina.getSelectedItem()==null){
            JOptionPane.showMessageDialog(null, "Campo em falta ");
        } else {
            x++;
            Docente doce = new Docente();
            doce.setNome(Txtnome_docente.getText());
            doce.setIdade((Integer) Idade.getValue());
            doce.setGenero(Sexo.getSelectedItem().toString());
            doce.setAltura(altura.getText());
            doce.setPeso(peso.getText());
            doce.setEstado_civil(Estado.getSelectedItem().toString());
            doce.setFuncao_exercida(Txt_funcao.getSelectedItem().toString());
            doce.setDisciplina(Txt_disciplina.getSelectedItem().toString());
            doce.setTurma(turma.getSelectedItem().toString());
            doce.setSalario(salario.getText());
            doce.setNumero_docente(x);
           
            num.setValue(x);
            docentes.add(doce);
            JOptionPane.showMessageDialog(null, doce.salvar(docentes));
            

            JOptionPane.showMessageDialog(null, "Docente Cadastrado com Sucesso");
            Txtnome_docente.setText(null);
            Idade.setValue(6);
            altura.getText();

        }
    }//GEN-LAST:event_Botao_registrar_docenteActionPerformed

    private void Txtnome_docenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txtnome_docenteKeyTyped
           String s = "0123456789"+",.@.º|#?%";
        if (s.contains(evt.getKeyChar()+"")) {
            evt.consume();
        }
    }//GEN-LAST:event_Txtnome_docenteKeyTyped

    private void Txtnome_docenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtnome_docenteActionPerformed

    }//GEN-LAST:event_Txtnome_docenteActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
       Principal principal = new Principal();
       principal.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void salarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salarioKeyTyped
           String s = "0123456789"+"";
        if (!s.contains(evt.getKeyChar()+"")) {
            evt.consume();
        }
    }//GEN-LAST:event_salarioKeyTyped

    private void Txt_funcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_funcaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_funcaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Registrar_docente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Registrar_docente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Registrar_docente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Registrar_docente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Registrar_docente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_actualizar_dados_docente;
    private javax.swing.JButton Botao_registrar_docente;
    private javax.swing.JComboBox Estado;
    private javax.swing.JSpinner Idade;
    private javax.swing.JButton Listar_docente;
    private javax.swing.JComboBox Sexo;
    private javax.swing.JTable Tabela;
    private javax.swing.JComboBox Txt_disciplina;
    private javax.swing.JTextField Txt_disciplina1;
    private javax.swing.JComboBox Txt_funcao;
    private javax.swing.JTextField Txtnome_docente;
    private javax.swing.JFormattedTextField altura;
    private javax.swing.JButton botao_consultar_docente;
    private javax.swing.JButton botao_eliminar_docente;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner num;
    private javax.swing.JFormattedTextField peso;
    private javax.swing.JTextField salario;
    private javax.swing.JComboBox turma;
    private javax.swing.JTextField txt_nome_consultar_docente;
    private javax.swing.JLabel txtturma1;
    private javax.swing.JLabel txtturma2;
    private javax.swing.JLabel txtturma3;
    // End of variables declaration//GEN-END:variables
}
