/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colegio;

import java.util.ArrayList;
import javax.sound.midi.SysexMessage;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emanueldemarao
 */
public class Menu_registrar_Estudante extends javax.swing.JFrame {

    int x = 0;
    ArrayList<Estudante> estudantes = new ArrayList();
    ArrayList<Turma> turmas = new ArrayList();
    ArrayList<Curso> cursos = new ArrayList();
    /**
     * Creates new form Menu_registrar_Estudante
     */
    public Menu_registrar_Estudante() {
        initComponents();
        
        estudantes =new Estudante().ler();
        for(Estudante e:estudantes) {
          System.out.print("oi");
        }
        turmas = new Turma().ler();
       cursos = new Curso().ler();
        Transferir_dados_turmas();
        Transferir_dados_cursos();
        
        for( Estudante e: estudantes) {
            x = e.getNumero_estudante();
        }
        
        
    }
    // receber dads do combobox turma
    public void Transferir_dados_turmas() {
        for(Turma t: turmas) {
            turma.addItem(t.getDescricao());
        }
        
    }public void Transferir_dados_cursos() {
        for(Curso c: cursos) {
            curso.addItem(c.getDescricao());
        }
        
    }
     
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Txtnome = new javax.swing.JTextField();
        Sexo = new javax.swing.JComboBox();
        Estado = new javax.swing.JComboBox();
        Idade = new javax.swing.JSpinner();
        Botao_registrar = new javax.swing.JButton();
        altura = new javax.swing.JFormattedTextField();
        peso = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        txtturma = new javax.swing.JLabel();
        turma = new javax.swing.JComboBox();
        curso = new javax.swing.JComboBox();
        botao_consultar_estudante = new javax.swing.JButton();
        botao_eliminar_estudante = new javax.swing.JButton();
        Botao_actualizar_dados_estudante = new javax.swing.JButton();
        txt_nome_consultar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Listar = new javax.swing.JButton();
        num = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 4, 58));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOME");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("IDADE");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ESTADO CIVIL");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("GÊNERO");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PESO(KG)");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ALTURA(M)");

        Txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtnomeActionPerformed(evt);
            }
        });
        Txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtnomeKeyTyped(evt);
            }
        });

        Sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));

        Estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro", "Casado" }));

        Idade.setModel(new javax.swing.SpinnerNumberModel(6, 6, 70, 1));

        Botao_registrar.setText("REGISTRAR");
        Botao_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_registrarActionPerformed(evt);
            }
        });

        try {
            altura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            peso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("CURSO");

        txtturma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtturma.setForeground(new java.awt.Color(255, 255, 255));
        txtturma.setText("TURMA");

        curso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        botao_consultar_estudante.setText("CONSULTAR");
        botao_consultar_estudante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_consultar_estudanteMouseClicked(evt);
            }
        });
        botao_consultar_estudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_consultar_estudanteActionPerformed(evt);
            }
        });

        botao_eliminar_estudante.setText("ELIMINAR");
        botao_eliminar_estudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_eliminar_estudanteActionPerformed(evt);
            }
        });

        Botao_actualizar_dados_estudante.setText("ACTUALIZAR DADOS");
        Botao_actualizar_dados_estudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_actualizar_dados_estudanteActionPerformed(evt);
            }
        });

        txt_nome_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nome_consultarActionPerformed(evt);
            }
        });
        txt_nome_consultar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nome_consultarKeyTyped(evt);
            }
        });

        Listar.setText("LISTAR");
        Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarActionPerformed(evt);
            }
        });

        num.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("NÚMERO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Botao_registrar)
                        .addGap(18, 18, 18)
                        .addComponent(botao_eliminar_estudante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Botao_actualizar_dados_estudante)
                        .addGap(18, 18, 18)
                        .addComponent(Listar)
                        .addGap(20, 20, 20)
                        .addComponent(botao_consultar_estudante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_nome_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(curso, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtturma)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(turma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(26, 26, 26)
                                .addComponent(jLabel13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(Idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Sexo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txtnome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(188, 188, 188)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10)
                    .addComponent(Txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtturma)
                    .addComponent(turma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao_registrar)
                    .addComponent(botao_eliminar_estudante)
                    .addComponent(Botao_actualizar_dados_estudante)
                    .addComponent(txt_nome_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_consultar_estudante)
                    .addComponent(Listar))
                .addGap(61, 61, 61))
        );

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "IDADE", "GÊNERO", "ALTURA", "PESO", "ESTADO CIVIL", "NÚMERO", "CURSO", "TURMA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);
        if (Tabela.getColumnModel().getColumnCount() > 0) {
            Tabela.getColumnModel().getColumn(0).setResizable(false);
            Tabela.getColumnModel().getColumn(1).setResizable(false);
            Tabela.getColumnModel().getColumn(2).setResizable(false);
            Tabela.getColumnModel().getColumn(3).setResizable(false);
            Tabela.getColumnModel().getColumn(4).setResizable(false);
            Tabela.getColumnModel().getColumn(5).setResizable(false);
            Tabela.getColumnModel().getColumn(6).setResizable(false);
        }

        jMenu1.setText("MENU");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Botao_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_registrarActionPerformed
        if (Txtnome.getText().equals("")
                || altura.getText().equals(" ,")
                || peso.getText().equals("")
                || altura.getText().equals("")
                || curso.getSelectedItem().equals(null) ){
            JOptionPane.showMessageDialog(null, "Campo em falta ");
        } else {
            x++;
            Estudante estud = new Estudante();
            estud.setNome(Txtnome.getText());
            estud.setIdade((Integer) Idade.getValue());
            estud.setGenero(Sexo.getSelectedItem().toString());
            estud.setAltura(altura.getText());
            estud.setPeso(peso.getText());
            estud.setEstado_civil(Estado.getSelectedItem().toString());
            estud.setTurma(turma.getSelectedItem().toString());
            estud.setCurso(curso.getSelectedItem().toString());
            estud.setNumero_estudante(x);
            num.setValue(x);

            estudantes.add(estud);
            JOptionPane.showMessageDialog(null, estud.salvar(estudantes));

            JOptionPane.showMessageDialog(null, "Estudante Cadastrado com Sucesso");
            Txtnome.setText(null);
            Idade.setValue(6);

        }
    }//GEN-LAST:event_Botao_registrarActionPerformed

    private void botao_consultar_estudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_consultar_estudanteActionPerformed
         
        if (txt_nome_consultar.getText().equals(null)) {
            JOptionPane.showMessageDialog(null, "Digite o nome para ser pesquisado");
        }
        else{
            txt_nome_consultar.requestFocus();


            DefaultTableModel t = (DefaultTableModel) Tabela.getModel();
             int linhas_tabela = t.getRowCount();

            for (int x = linhas_tabela - 1; x >= 0; x--) {
                t.removeRow(x);
            }

            // Inicializar a extrutura de estudantes

            // popular a extrutura de estudantes
            //estudantes = new Estudante().ler();


            for (Estudante consulta : estudantes) {
                if (consulta.getNome().contains(txt_nome_consultar.getText())) {
                    Object[] dados_estudante
                            = {
                                consulta.getNome(), consulta.getIdade(), consulta.getGenero(),
                                consulta.getAltura(), consulta.getPeso(), consulta.getEstado_civil(),
                                consulta.getNumero_estudante(), consulta.getCurso(), consulta.getTurma()
                            };
                    
                    t.addRow(dados_estudante);
                }
            }
        }
    }//GEN-LAST:event_botao_consultar_estudanteActionPerformed

    private void txt_nome_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nome_consultarActionPerformed
        
    }//GEN-LAST:event_txt_nome_consultarActionPerformed

    private void botao_eliminar_estudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_eliminar_estudanteActionPerformed

        int index = Tabela.getSelectedRow();
        Estudante estud = new Estudante();
        Tabela.getSelectedRow();
        if (Tabela.getSelectedRow() != -1) {
            DefaultTableModel conteudos = (DefaultTableModel) Tabela.getModel();
            String nome_estudante = conteudos.getValueAt(index, 0).toString();
            for (Estudante selecionado : estudantes) {
                if (selecionado.getNome().equals(nome_estudante)) {
                    estudantes.remove(selecionado);
                      JOptionPane.showMessageDialog(null, estud.salvar(estudantes));
                    break;
                }
            }
            conteudos.removeRow(Tabela.getSelectedRow());

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para eliminar algum estudante");
        }

    }//GEN-LAST:event_botao_eliminar_estudanteActionPerformed

    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed
        DefaultTableModel t = (DefaultTableModel) Tabela.getModel();
        int linhas = t.getRowCount();

        for (int i = linhas - 1; i >= 0; i--) {
            t.removeRow(i);
        }

        for (Estudante dados : estudantes) {

            Object[] lista_estudante
                    = {
                        dados.getNome(), dados.getIdade(), dados.getGenero(),
                        dados.getAltura(), dados.getPeso(), dados.getEstado_civil(),
                        dados.getNumero_estudante(), dados.getCurso(), dados.getTurma()
                    };
            t.addRow(lista_estudante);
        }
    }//GEN-LAST:event_ListarActionPerformed

    private void TxtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtnomeActionPerformed

    }//GEN-LAST:event_TxtnomeActionPerformed

    private void TxtnomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtnomeKeyTyped
        String s = "0123456789"+",.@.º|#?%";
        if (s.contains(evt.getKeyChar()+"")) {
            evt.consume();
        }
    }//GEN-LAST:event_TxtnomeKeyTyped

    private void Botao_actualizar_dados_estudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_actualizar_dados_estudanteActionPerformed
        if (Tabela.getSelectedRow() != -1) {
            //vai trocar os dados
            DefaultTableModel eliminar = (DefaultTableModel) Tabela.getModel();
            Estudante estud = new Estudante();
            for(Estudante e: estudantes) {
                if(eliminar.getValueAt(Tabela.getSelectedRow(),6).equals(e.getNumero_estudante())){
   
                     e.setNome(Txtnome.getText());
                     e.setIdade((Integer) Idade.getValue());
                     e.setGenero(Sexo.getSelectedItem().toString());
                     e.setAltura(altura.getText());
                     e.setPeso(peso.getText());
                     e.setEstado_civil(Estado.getSelectedItem().toString());
                     e.setTurma(turma.getSelectedItem().toString());
                     e.setCurso(curso.getSelectedItem().toString());
            
                    
                    estud.salvar(estudantes);
                    
                }
            }
            Tabela.setValueAt(Txtnome.getText(), Tabela.getSelectedRow(), 0);
            
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para editar");
        }

    }//GEN-LAST:event_Botao_actualizar_dados_estudanteActionPerformed

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
        if (Tabela.getSelectedRow() != -1) {
            Txtnome.setText(Tabela.getValueAt(Tabela.getSelectedRow(), 0).toString());

        } else {

            JOptionPane.showMessageDialog(null, "selecione uma linha  para editar");

        }
    }//GEN-LAST:event_TabelaMouseClicked

    private void botao_consultar_estudanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_consultar_estudanteMouseClicked

    }//GEN-LAST:event_botao_consultar_estudanteMouseClicked

    private void pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoActionPerformed

    }//GEN-LAST:event_pesoActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
       Principal principal = new Principal();
       principal.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void txt_nome_consultarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nome_consultarKeyTyped
          String s = "0123456789"+",.@.º|#?%";
        if (s.contains(evt.getKeyChar()+"")) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_nome_consultarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_registrar_Estudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_registrar_Estudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_registrar_Estudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_registrar_Estudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_registrar_Estudante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_actualizar_dados_estudante;
    private javax.swing.JButton Botao_registrar;
    private javax.swing.JComboBox Estado;
    private javax.swing.JSpinner Idade;
    private javax.swing.JButton Listar;
    private javax.swing.JComboBox Sexo;
    private javax.swing.JTable Tabela;
    private javax.swing.JTextField Txtnome;
    private javax.swing.JFormattedTextField altura;
    private javax.swing.JButton botao_consultar_estudante;
    private javax.swing.JButton botao_eliminar_estudante;
    private javax.swing.JComboBox curso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner num;
    private javax.swing.JFormattedTextField peso;
    private javax.swing.JComboBox turma;
    private javax.swing.JTextField txt_nome_consultar;
    private javax.swing.JLabel txtturma;
    // End of variables declaration//GEN-END:variables
}
