/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colegio;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emanueldemarao
 */
public class Menu_Registrar_disciplina extends javax.swing.JFrame {

    ArrayList<Disciplina> disciplinas = new ArrayList();
     ArrayList<Curso> cursos = new ArrayList();
      ArrayList<Docente> docentes = new ArrayList();

    /**
     * Creates new form Menu_Registrar_disciplina
     */
    public Menu_Registrar_disciplina() {
        initComponents();
         docentes = new Docente().ler();
       cursos = new Curso().ler();
        disciplinas = new Disciplina().ler();
        transferir_dados_docente();
        transferir_dados_curso();
    }
    
    public void transferir_dados_docente() {
        for(Docente d: docentes) {
            prof.addItem(d.getNome());
        }
    }
    
    public void transferir_dados_curso() {
        for(Curso c: cursos) {
            TXTcursos.addItem(c.getDescricao());
        }
    }
    
    
    
    
    
        
    
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Txt_descricao_disciplina = new javax.swing.JTextField();
        Registrar_Turma = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        botao_actualizar_disciplina = new javax.swing.JButton();
        botao_eliminar_curso = new javax.swing.JButton();
        txt_pesquisar_disciplina = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Listar_disciplina = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TXTcursos = new javax.swing.JComboBox();
        prof = new javax.swing.JComboBox();
        Txt_carga_horaria = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 4, 58));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DESCRIÇÃO");

        Txt_descricao_disciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_descricao_disciplinaActionPerformed(evt);
            }
        });
        Txt_descricao_disciplina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_descricao_disciplinaKeyTyped(evt);
            }
        });

        Registrar_Turma.setText("REGISTRAR");
        Registrar_Turma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registrar_TurmaActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("PROFESSOR");

        botao_actualizar_disciplina.setText("CONSULTAR");
        botao_actualizar_disciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_actualizar_disciplinaMouseClicked(evt);
            }
        });
        botao_actualizar_disciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_actualizar_disciplinaActionPerformed(evt);
            }
        });

        botao_eliminar_curso.setText("ELIMINAR");
        botao_eliminar_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_eliminar_cursoActionPerformed(evt);
            }
        });

        txt_pesquisar_disciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pesquisar_disciplinaActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\emanu\\AppData\\Local\\Temp\\icons8_search_client_48px.png")); // NOI18N

        Listar_disciplina.setText("LISTAR");
        Listar_disciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listar_disciplinaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cursos");

        Txt_carga_horaria.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CARGA-HORÁRIA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(Registrar_Turma)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(botao_eliminar_curso)
                                        .addGap(33, 33, 33)
                                        .addComponent(Listar_disciplina)
                                        .addGap(18, 18, 18)
                                        .addComponent(botao_actualizar_disciplina)
                                        .addGap(17, 17, 17))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Txt_carga_horaria, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel15)
                                        .addGap(36, 36, 36)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_pesquisar_disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(17, 17, 17)
                        .addComponent(Txt_descricao_disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addComponent(TXTcursos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Txt_descricao_disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TXTcursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Txt_carga_horaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Registrar_Turma)
                            .addComponent(botao_eliminar_curso)
                            .addComponent(Listar_disciplina)
                            .addComponent(botao_actualizar_disciplina)
                            .addComponent(txt_pesquisar_disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DESCRÇÃO", "CARGA HORÁRIA", "CURSO", "PROFESSOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);

        jMenu1.setText("MENU");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_descricao_disciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_descricao_disciplinaActionPerformed

    }//GEN-LAST:event_Txt_descricao_disciplinaActionPerformed

    private void Txt_descricao_disciplinaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_descricao_disciplinaKeyTyped
            String s = "0123456789"+",.@.º|#?%";
        if (s.contains(evt.getKeyChar()+"")) {
            evt.consume();
        }
    }//GEN-LAST:event_Txt_descricao_disciplinaKeyTyped

    private void Registrar_TurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registrar_TurmaActionPerformed

        if (Txt_descricao_disciplina.getText().equals("") || TXTcursos.getSelectedItem()==null || prof.getSelectedItem()==null ) {
            System.out.print("campo faltando cara");
            JOptionPane.showMessageDialog(null, "Campo em falta ");
        } else {

            Disciplina d = new Disciplina();
            d.setDescricao(Txt_descricao_disciplina.getText());
            d.setCargaHoraria((Integer) Txt_carga_horaria.getValue());
            d.setCurso(TXTcursos.getSelectedItem().toString());
            d.setProfessor(prof.getSelectedItem().toString());

            disciplinas.add(d);
            JOptionPane.showMessageDialog(null, d.salvar(disciplinas));

            JOptionPane.showMessageDialog(null, "Turma cadastrada com Sucesso");
            Txt_descricao_disciplina.setText(null);

        }
    }//GEN-LAST:event_Registrar_TurmaActionPerformed

    private void botao_actualizar_disciplinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_actualizar_disciplinaMouseClicked

    }//GEN-LAST:event_botao_actualizar_disciplinaMouseClicked

    private void botao_actualizar_disciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_actualizar_disciplinaActionPerformed
        if (txt_pesquisar_disciplina.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o nome para ser pesquisado");
        }
        txt_pesquisar_disciplina.requestFocus();
        DefaultTableModel t = (DefaultTableModel) Tabela.getModel();
        int linhas_tabela = t.getRowCount();

        for (int x = linhas_tabela - 1; x >= 0; x--) {
            t.removeRow(x);
        }

        for (Disciplina consulta : disciplinas) {
            if (consulta.getDescricao().contains(txt_pesquisar_disciplina.getText())) {
                Object[] dados_turma
                        = {
                            consulta.getDescricao(),consulta.getCargaHoraria(),
                            consulta.getCurso(),
                            consulta.getProfessor()
                        };
                t.addRow(dados_turma);
                txt_pesquisar_disciplina.setText(null);
            }
        }
    }//GEN-LAST:event_botao_actualizar_disciplinaActionPerformed

    private void botao_eliminar_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_eliminar_cursoActionPerformed

        int index = Tabela.getSelectedRow();
        Tabela.getSelectedRow();
        if (Tabela.getSelectedRow() != -1) {
            DefaultTableModel conteudos = (DefaultTableModel) Tabela.getModel();
            String nome_disciplina = conteudos.getValueAt(index, 0).toString();
            for (Disciplina selecionado : disciplinas) {
                if (selecionado.getDescricao().equals(nome_disciplina)) {
                    disciplinas.remove(selecionado);
                    break;
                }
            }
            conteudos.removeRow(Tabela.getSelectedRow());

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para eliminar algum estudante");
        }
    }//GEN-LAST:event_botao_eliminar_cursoActionPerformed

    private void Listar_disciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listar_disciplinaActionPerformed
        DefaultTableModel t = (DefaultTableModel) Tabela.getModel();
        int linhas = t.getRowCount();

        for (int i = linhas - 1; i >= 0; i--) {
            t.removeRow(i);
        }

        for (Disciplina dados : disciplinas) {

            Object[] lista_turmas
                    = {
                        dados.getDescricao(),
                        dados.getCargaHoraria(),
                        dados.getCurso(),
                        dados.getProfessor()
                        

                    };
            t.addRow(lista_turmas);
        }
    }//GEN-LAST:event_Listar_disciplinaActionPerformed

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
        if (Tabela.getSelectedRow() != -1) {
            Txt_descricao_disciplina.setText(Tabela.getValueAt(Tabela.getSelectedRow(), 0).toString());

        } else {

            JOptionPane.showMessageDialog(null, "selecione uma linha  para editar");

        }
    }//GEN-LAST:event_TabelaMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
     Principal principal = new Principal();
       principal.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void txt_pesquisar_disciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pesquisar_disciplinaActionPerformed

    }//GEN-LAST:event_txt_pesquisar_disciplinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Registrar_disciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Registrar_disciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Registrar_disciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Registrar_disciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Registrar_disciplina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Listar_disciplina;
    private javax.swing.JButton Registrar_Turma;
    private javax.swing.JComboBox TXTcursos;
    private javax.swing.JTable Tabela;
    private javax.swing.JSpinner Txt_carga_horaria;
    private javax.swing.JTextField Txt_descricao_disciplina;
    private javax.swing.JButton botao_actualizar_disciplina;
    private javax.swing.JButton botao_eliminar_curso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox prof;
    private javax.swing.JTextField txt_pesquisar_disciplina;
    // End of variables declaration//GEN-END:variables
}
