/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colegio;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emanueldemarao
 */
public class Menu_Registrar_Turma extends javax.swing.JFrame {
    
     int x = 0;
    ArrayList<Turma> turmas = new ArrayList();
    ArrayList<Docente> docentes = new ArrayList();
    /**
     * Creates new form Menu_Registrar_Turma
     */
    public Menu_Registrar_Turma() {
        initComponents();
        docentes = new Docente().ler();
        turmas = new Turma().ler();
        Transferir_dados_Docentes();
         for( Turma t: turmas) {
            x = t.getNumero();
        }
    }
    public void Transferir_dados_Docentes() {
        for(Docente d: docentes) {
           director.addItem(d.getNome());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Txt_descricao_turma = new javax.swing.JTextField();
        director = new javax.swing.JComboBox();
        Registrar_Turma = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        botao_consultar_cursos = new javax.swing.JButton();
        botao_eliminar_curso = new javax.swing.JButton();
        txt_pesquisar_turma = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Listar_Turmas = new javax.swing.JButton();
        numm = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        Txtturno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 4, 58));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DESCRIÇÃO");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DIRECTOR DE TURMA");

        Txt_descricao_turma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_descricao_turmaActionPerformed(evt);
            }
        });
        Txt_descricao_turma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_descricao_turmaKeyTyped(evt);
            }
        });

        director.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        director.setToolTipText("");

        Registrar_Turma.setText("REGISTRAR");
        Registrar_Turma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registrar_TurmaActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("TURNO");

        botao_consultar_cursos.setText("CONSULTAR");
        botao_consultar_cursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_consultar_cursosMouseClicked(evt);
            }
        });
        botao_consultar_cursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_consultar_cursosActionPerformed(evt);
            }
        });

        botao_eliminar_curso.setText("ELIMINAR");
        botao_eliminar_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_eliminar_cursoActionPerformed(evt);
            }
        });

        txt_pesquisar_turma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pesquisar_turmaActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\emanu\\AppData\\Local\\Temp\\icons8_search_client_48px.png")); // NOI18N

        Listar_Turmas.setText("LISTAR");
        Listar_Turmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listar_TurmasActionPerformed(evt);
            }
        });

        numm.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("NÚMERO");

        Txtturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtturnoActionPerformed(evt);
            }
        });
        Txtturno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtturnoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Registrar_Turma)
                                .addGap(36, 36, 36)
                                .addComponent(botao_eliminar_curso)
                                .addGap(32, 32, 32)
                                .addComponent(Listar_Turmas))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Txtturno, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botao_consultar_cursos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_pesquisar_turma, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel16))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numm, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Txt_descricao_turma, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel12)))
                        .addGap(18, 18, 18)
                        .addComponent(director, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Txt_descricao_turma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(director, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(numm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(Txtturno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registrar_Turma)
                    .addComponent(botao_eliminar_curso)
                    .addComponent(botao_consultar_cursos)
                    .addComponent(Listar_Turmas)
                    .addComponent(txt_pesquisar_turma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DESCRÇÃO", "NUMERO", "TURNO", "DIRECTOR DE TURMA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);

        jMenu1.setText("MENU");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
        if (Tabela.getSelectedRow() != -1) {
            Txt_descricao_turma.setText(Tabela.getValueAt(Tabela.getSelectedRow(), 0).toString());

        } else {

            JOptionPane.showMessageDialog(null, "selecione uma linha  para editar");

        }
    }//GEN-LAST:event_TabelaMouseClicked

    private void Listar_TurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listar_TurmasActionPerformed
        DefaultTableModel t = (DefaultTableModel) Tabela.getModel();
        int linhas = t.getRowCount();

        for (int i = linhas-1; i >=0; i--) {
            t.removeRow(i);
        }

        for (Turma dados : turmas) {

            Object[] lista_turmas
            = {
                dados.getDescricao(), dados.getNumero(), dados.getTurno(),
                dados.getDirector_turma()
              
                
            };
            t.addRow(lista_turmas);
        }
    }//GEN-LAST:event_Listar_TurmasActionPerformed

    private void txt_pesquisar_turmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pesquisar_turmaActionPerformed

    }//GEN-LAST:event_txt_pesquisar_turmaActionPerformed

    private void botao_eliminar_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_eliminar_cursoActionPerformed

        int index = Tabela.getSelectedRow();
        Tabela.getSelectedRow();
        Turma turm = new Turma();
        if (Tabela.getSelectedRow() != -1) {
            DefaultTableModel conteudos = (DefaultTableModel) Tabela.getModel();
            String nome_turma = conteudos.getValueAt(index, 0).toString();
            for (Turma selecionado : turmas) {
                if (selecionado.getDescricao().equals(nome_turma)) {
                    turmas.remove(selecionado);
                     JOptionPane.showMessageDialog(null, turm.salvar(turmas));
                    break;
                }
            }
            conteudos.removeRow(Tabela.getSelectedRow());

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para eliminar algum estudante");
        }
    }//GEN-LAST:event_botao_eliminar_cursoActionPerformed

    private void botao_consultar_cursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_consultar_cursosActionPerformed
        if(txt_pesquisar_turma.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o nome para ser pesquisado");
        }
        txt_pesquisar_turma.requestFocus();
        DefaultTableModel t = (DefaultTableModel) Tabela.getModel();
        int linhas_tabela = t.getRowCount();

        for (int x = linhas_tabela - 1; x >= 0; x--) {
            t.removeRow(x);
        }

        for (Turma consulta : turmas) {
            if (consulta.getDescricao().contains(txt_pesquisar_turma.getText())) {
                Object[] dados_turma
                = {
                    consulta.getDescricao(), consulta.getNumero(),
                    consulta.getTurno(),
                    consulta.getDirector_turma()
                };
                t.addRow(dados_turma);
                txt_pesquisar_turma.setText(null);
            }
        }
    }//GEN-LAST:event_botao_consultar_cursosActionPerformed

    private void botao_consultar_cursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_consultar_cursosMouseClicked

    }//GEN-LAST:event_botao_consultar_cursosMouseClicked

    private void Registrar_TurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registrar_TurmaActionPerformed
       
      
         
        if(Txt_descricao_turma.getText().equals("")
            || Txt_descricao_turma.getText().equals("")
            || Txtturno.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo em falta ");
        } else {
            x++;
            Turma t = new Turma();
            t.setDescricao(Txt_descricao_turma.getText());
            t.setDirector_turma(director.getSelectedItem().toString());
            t.setTurno(Txtturno.getText());
            t.setNumero(x);

            numm.setValue(x);
          

            turmas.add(t);
            JOptionPane.showMessageDialog(null,t.salvar(turmas));

            JOptionPane.showMessageDialog(null, "Turma cadastrada com Sucesso");
            Txt_descricao_turma.setText(null);
            numm.setValue(0);
            Txt_descricao_turma.setText(null);
            Txtturno.setText(null);

        }
    }//GEN-LAST:event_Registrar_TurmaActionPerformed

    private void Txt_descricao_turmaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_descricao_turmaKeyTyped
        String s = "0123456789"+",.@.º|#?%";
        if (s.contains(evt.getKeyChar()+"")) {
            evt.consume();
        }
    }//GEN-LAST:event_Txt_descricao_turmaKeyTyped

    private void Txt_descricao_turmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_descricao_turmaActionPerformed

    }//GEN-LAST:event_Txt_descricao_turmaActionPerformed

    private void TxtturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtturnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtturnoActionPerformed

    private void TxtturnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtturnoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtturnoKeyTyped

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
       Principal principal = new Principal();
       principal.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Registrar_Turma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Registrar_Turma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Registrar_Turma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Registrar_Turma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Registrar_Turma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Listar_Turmas;
    private javax.swing.JButton Registrar_Turma;
    private javax.swing.JTable Tabela;
    private javax.swing.JTextField Txt_descricao_turma;
    private javax.swing.JTextField Txtturno;
    private javax.swing.JButton botao_consultar_cursos;
    private javax.swing.JButton botao_eliminar_curso;
    private javax.swing.JComboBox director;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner numm;
    private javax.swing.JTextField txt_pesquisar_turma;
    // End of variables declaration//GEN-END:variables
}
